
export default new Map([
["src/data/authors/main-author/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/otherPages/en/privacy-policy/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2FotherPages%2Fen%2Fprivacy-policy%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/k3s-raspberry-pi-the-perfect-diy-kubernetes-cluster/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Fk3s-raspberry-pi-the-perfect-diy-kubernetes-cluster%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/why-split-dns-is-a-trap-and-you-shouldn-t-fall-for-it/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Fwhy-split-dns-is-a-trap-and-you-shouldn-t-fall-for-it%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/argocd-hub-spoke-automation/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Fargocd-hub-spoke-automation%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/portfolio-website/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Fportfolio-website%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/mr-builders/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Fmr-builders%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/custom-report-generator/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Fcustom-report-generator%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/rke-2-cluster-factory/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Frke-2-cluster-factory%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/production-homelab-part-2-vps/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Fproduction-homelab-part-2-vps%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/projects/en/home-lab-production-workflow/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fprojects%2Fen%2Fhome-lab-production-workflow%2Findex.mdx&astroContentModuleFlag=true")]]);
		