version: "3.9"

services:
  web:
    image: andrew-portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: andrew-portfolio-api:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_DEV_MODE=true
      - API_INTERNAL_TOKEN
      - OPENROUTER_API_KEY
    labels:
      # Middleware: inject header with your secret (from env)
      - traefik.http.middlewares.api-headers.headers.customrequestheaders.X-Internal-Auth=${API_INTERNAL_TOKEN}
      # Attach middleware to router
      - traefik.http.routers.api.middlewares=api-headers@docker
