version: "3.9"

services:
  web:
    image: andrew-portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: andrew-portfolio-api:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - INTERNAL_API_TOKEN
      - OPENROUTER_API_KEY
    ports:
      - "4321:4321"  # Expose API for local testing (remove in production if undesired)
    labels:
      - "traefik.http.middlewares.internal-api.headers.customrequestheaders.X-Internal-Secret=${INTERNAL_API_TOKEN}"
      - "traefik.http.routers.andrew-api.middlewares=internal-api@docker"
