services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: andrew-portfolio-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4321
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    image: andrew-portfolio-frontend
    restart: unless-stopped
    ports:
      - "8080:80" # public site
    depends_on:
      - backend
