services:
  web:
    image: andrew-portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_DEV_MODE=false
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - INTERNAL_API_TOKEN
      - OPENROUTER_API_KEY
    expose:
      - "4321" # internal port; Traefik will route to this
    labels:
      - "traefik.http.middlewares.api-headers.headers.customrequestheaders.X-Internal-Auth=${INTERNAL_API_TOKEN}"
      - traefik.http.routers.api.middlewares=api-headers@docker
