services:
  web:
    image: andrew-portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=prduoction
      - PUBLIC_DEV_ODME=false
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN} # ← Add the = and ${...}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./middlewares.yml:/etc/traefik/dynamic/middlewares.yml:ro
    expose:
      - "4321" # internal port; Traefik will route to this
    labels:
      - "traefik.http.routers.*.middlewares: api-headers@file"
